# Tomcat
server:
  port: 9377
spring:
  application:
    name: crabc-api
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true  # 全局启用虚拟线程
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    core:
      recycler-pool: thread-local  # Jackson3性能恢复
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://8.138.199.189:33061/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Crabc123.
# mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cn.crabc.core.admin.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  autoRuntimeDialect: true   # 开启多数据源分页识别